# -*- coding: utf-8 -*-
"""Python3-function_tuple_dict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XzBj7ruyiaV4u0_mQw_NGAIOVShkV_AW

# Python Basic 3
Functions, tuples, dictionaries, and data processing

Referensi Tambahan:
- https://docs.python.org/3.8/
- https://docs.python.org/id/3.8/tutorial/


## Materi

- defining and using functions;
- different ways of passing arguments;
- name scopes;
- tuples and dictionaries;
- data processing.

# Function
![function.png](attachment:function.png)
- when you invoke a function, Python remembers the place where it happened and jumps into the invoked function;
- the body of the function is then executed;
- reaching the end of the function forces Python to return to the place directly after the point of invocation.
"""

# Motivasi function adalah perulangan kode

print("Angka 1 :")
a = int(input())
print(a)

print("Angka 2 :")
b = int(input())
print(b)

print("Angka 3 :")
c = int(input())
print(c)

"""Sintaks Function:

```python
def functionName():
    functionBody
```
"""

def inputAngka():
    print("Input Angka :")
    a = int(input())
    print(a)

print("Start disini... ")

inputAngka()
inputAngka()
inputAngka()

print("Stop disini... ")

"""### Parametrized functions"""

def pesan(m):
    print("Pesan ",m.lower())

pesan("Hallo")
pesan("Namanya siapa ?")

def pesan(nama, nohp):
    print("Nama : ",nama, "No Hp : ",nohp)

pesan("Abu", 123)
pesan("Abu", "0817244")

def tambahUsia(nama, umur):
    umur = umur + 0.5
    print(nama, umur)

tambahUsia("Abu Salam", 30)

"""### Posisi Parameter


"""

def perkenalan(namaDepan, namaBelakang):
    print("Hallo namanya adalah : ", namaDepan, namaBelakang)

perkenalan("Abu","Salam")
perkenalan("Dhita","Aulia")

perkenalan(namaDepan = "Abu2", namaBelakang = "salam2")
perkenalan(namaBelakang = "aulia2", namaDepan = "dhita2")

def jumlah(a, b, c):
    print(a, "+", b, "+", c, "=", a + b + c)

jumlah(5,5,4)

"""## Default parameter"""

def introduction(firstName="John",lastName="Smith"):
    print("Hello, my name is", firstName, lastName)

#Call the Function here
introduction(firstName="Abu")
introduction(firstName="Abu", lastName="Salam")
introduction("Abu", lastName="Salam")

def introductionLengkap(firstName, lastName, middleName="Guntur"):
    print("Hello, my name is", firstName, middleName, lastName)

#Call the Function here
introductionLengkap(firstName="Abu", lastName="Salam", middleName="alex")

"""## Function dengan Return"""

def hitungLuasLingkaran(r):
    import math
    pi = math.pi
    luas = pi * r * r
    return luas

# buat sebuah fungsi untuk menghitung luas segitiga
def hitungLuasSegitiga(a,t):
    luas = 0.5 * a * t
    return luas


x = hitungLuasLingkaran(6)
y = hitungLuasSegitiga(5,10)

print(x)
print(y)

def boringFunction():
    print("'Boredom Mode' ON.")
    return 123

print("This Lesson is interesting!")
x = boringFunction()
print(x)
print("test")

def jumlah(a,b):
    c = a + b
    return c

a = jumlah(3,4)
print(a)

def strangeFunction(n):
    if(n % 2 == 0):
        return True

#Call the Function here

print(strangeFunction(4))
print(strangeFunction(3))

def sumOfList(lst):
    sum = 0

    for elem in lst:
        sum += elem

    return sum

#Call the Function here
x = sumOfList([2,2,2,2,2])
print(x)

def strangeListFunction(n):
    strangeList = []

    for i in range(0, n):
        print("Insert",i)
        strangeList.insert(0, i)
        print(strangeList)

    return strangeList

#Call the Function here
print("Hasil : ", strangeListFunction(10))

"""### Latihan

Your task is to write and test a function which takes one argument (a year) and returns `True` if the year is a leap year, or `False` otherwise.

The seed of the function is already sown in the skeleton code in the editor.

Note: we've also prepared a short testing code, which you can use to test your function.

The code uses two lists - one with the test data, and the other containing the expected results. The code will tell you if any of your results are invalid.

```python
def isYearLeap(year):
#
# put your code here
#

testData = [1900, 2000, 2016, 1987]
testResults = [False, True, True, False]
for i in range(len(testData)):
	yr = testData[i]
	print(yr,"->",end="")
	result = isYearLeap(yr)
	if result == testResults[i]:
		print("OK")
	else:
		print("Failed")
        
```

"""

# Function Test tahun Kabisat
def isYearLeap(year):
    if (year % 4) == 0:
        if (year % 100) == 0:
            if (year % 400) == 0:
                return True
            else:
                return False
        else:
            return True
    else:
        return False

testData = [1900, 2000, 2016, 1987,2004]
testResults = [False, True, True, False, True]
for i in range(len(testData)):
    yr = testData[i]
    print(yr,"->",end="")
    result = isYearLeap(yr)
    if result == testResults[i]:
        print("OK")
    else:
        print("Failed")

"""## Scope in Function"""

def scopeTest():
    print(a)
    b = 120
    print(b)

#Call the Function here

a = 90
scopeTest()

def myFunction():
    print("Do I know that variable?", var)

#Call the Function here
var = 1
myFunction()
print(var)

# The answer is: a variable existing outside a function
# has a scope inside the functions' bodies.

def myFunction():
    global var
    var = 2
    print("Do I know that variable?", var)

#Call the Function here
var = 1
myFunction()
print(var)

# There's a special Python method which can extend a variable's scope
# in a way which includes the functions' bodies
# (even if you want not only to read the values, but also to modify them).

def myFunction(n):
    print("I got", n)
    n += 1
    print("I have", n)

#Call the Function here
var = 1
myFunction(var)

print(var)

#changing the parameter's value doesn't propagate outside the function

"""# Some Function Examples

## BMI
(Body Mass Index)
"""

def bmi(weight, height):
    return weight / height ** 2

print(bmi(65, 1.69))

def bmi(weight, height):
    if height < 1.0 \
    or height > 2.5 \
    or weight < 20 \
    or weight > 200:
        return None

    return weight / height ** 2

print(bmi(70, 1.69))

"""## Segitiga"""

def isItATriangle(a, b, c):
    if a + b <= c:
        return False
    if b + c <= a:
        return False
    if c + a <= b:
        return False

    return True

#Call the Function here
print(isItATriangle(1,1,1))
print(isItATriangle(1,2,2))

def isItATriangle(a, b, c):
    return a + b > c and b + c > a and c + a > b

a = float(input("Enter the first side's length: "))
b = float(input("Enter the second side's length: "))
c = float(input("Enter the third side's length: "))

if isItATriangle(a, b, c):
    print("Congratulations - it can be a triangle.")
else:
    print("Sorry, it won't be a triangle.")

"""## Faktorial"""

def factorialFun(n):
    if n < 0:
        return None
    if n < 2:
        return 1

    product = 1
    for i in range(2, n + 1):
        product *= i
    return product

#Call the Function here
for n in range(1, 15): # testing
    print(n, factorialFun(n))

"""## Fibonacci"""

def fib(n):
    if n < 1:
         return None
    if n < 3:
        return 1

    elem1 = elem2 = 1
    sum = 0
    for i in range(3, n + 1):
        sum = elem1 + elem2
        elem1, elem2 = elem2, sum
    return sum

#Call the Function here
for n in range(1, 10): #testing
    print(n, ">", fib(n))

"""## Recursion"""

#recursion 1
def fib(n):
    if n < 1:
        return None
    if n < 3:
        return 1
    return fib(n - 1) + fib(n - 2)

for n in range(1, 10): # testing
    print(n, "->", fib(n))

#recursion 2

def fun(a):
    if a > 30:
        return 3
    else:
        return a + fun(a + 3)


print(fun(25))

"""#### Contoh Kasus Stop Word Removal"""

kalimat = "Ibu pergi ke pasar dengan Bapak"
stopw = ['ke','dengan','saya','dia']

def removeStop(sentence):
#     words = []
    words = [word for word in sentence.split() if word not in stopw]
#     for word in sentence.split():
#         if word not in stopw:
#             words.append(word)

    return ' '.join(words)

# print('ke' in kalimat.split())
kalimat_stop = removeStop(kalimat.lower())

print(kalimat_stop)
# output kalimat_stop: Ibu pergi pasar Bapak"

"""# Tuples and Dictionaries

##### List VS Tuple
List datanya bisa dirubah selama eksekusi program, sifatnya bernama mutable
Sebaliknya tuple tidak bisa, sifatnya dinamakan immutable. Persamaannya keduanya sama-sama bisa menyimpan banyak nilai sekaligus dalam satu tipe data (sequence type)

## Tuples
Tuples are ordered and unchangeable (immutable) collections of data. They can be thought of as immutable lists. They are written in round brackets:
"""

myTuple = (1, 2, True, "a string", (3, 4), [5, 6], None)
#Print Function here
print(myTuple)

myList = [1, 2, True, "a string", (3, 4), [5, 6], None]
#Print Function here
print(myList)

tup1 = (1,2,3,4)
tup2 = 1.0, .5, .25, .124

print(tup1)
print(tup2)

emptyTuple = ()
print(type(emptyTuple))

myTuple = (1, 10, 100, 1000)

print(myTuple[0])
print(myTuple[-1])
print(myTuple[1:])
print(myTuple[:-2])

for elem in myTuple:
    print(elem, end = " ")

myTuple = (1, 10, 100, 1000)

#Tuple operation ?

# myTuple.append(10000)
# del myTuple[0]
# myTuple[1] = -10

myTuple = (1, 10, 100)
print(type(myTuple))

#Tuple operation
print(myTuple[0])
print(myTuple[-1])
print(myTuple[1:])
print(myTuple[:-2])
# Print Function here

# Example 1
t1 = (1, 2, 3)
for elem in t1:
    print(elem)

# Example 2
t2 = (1, 2, 3, 4)
print(5 in t2)
print(5 not in t2)

# Example 3
t3 = (1, 2, 3, 5)
print(len(t3))

# Example 4
t4 = t1 + t2
t5 = t3 * 2

print(t4)
print(t5)

"""## Dictionaries

In Python's world, the word you look for is named a key. The word you get from the dictionary is called a value.

Dictionaries are unordered*, changeable (mutable), and indexed collections of data. (*In Python 3.6x dictionaries have become ordered by default.

This means that a dictionary is a set of key-value pairs. Note:

- each key must be unique - it's not possible to have more than one key of the same value;
- a key may be data of any type: it may be a number (integer or float), or even a string;
- a dictionary is not a list - a list contains a set of numbered values, while a dictionary holds pairs of values;
- the len() function works for dictionaries, too - it returns the numbers of key-value elements in the dictionary;
- a dictionary is a one-way tool - if you have an English-French dictionary, you can look for French equivalents of English terms, but not vice versa.
"""

kamus = {"cat" : "chat", "dog" : "chien", "horse" : "cheval"}
phoneNumbers = {'boss' : 5551234567, 'Suzy' : [22657854310,52852352]}
emptyDictionary = {}

print()
print(phoneNumbers)
print(emptyDictionary)

print(kamus['cat'])
print(phoneNumbers['Suzy'])
print(phoneNumbers['Suzy'][0])

dict = {"horse" : "cheval", "cat" : "chat", "dog" : "chien"}

for key in dict.keys():
    print(key,dict[key])

for key in sorted(dict.keys()):
    print(key, "->", dict[key])

"""### items and values"""

dict = {"cat" : "chat", "dog" : "chien", "horse" : "cheval"}

for english, french in dict.items():
    print(english, "->", french)

dict = {"cat" : "chat", "dog" : "chien", "horse" : "cheval"}

for french in dict.values():
    print(french)

dict = {"cat" : "chat", "dog" : "chien", "horse" : "cheval"}
words = ['cat', 'lion', 'horse','mouse']

for word in words:
    if word in dict:
        print(word, "->", dict[word])
    else:
        print(word, "is not in dictionary")

"""### Replace"""

dict = {"cat" : "chat", "dog" : "chien", "horse" : "cheval"}

dict['cat'] = 'minou'
print(dict)

"""### Adding new key"""

dict = {"cat" : "chat", "dog" : "chien", "horse" : "cheval"}

dict['swan'] = 'cygne'
dict['animal'] = 'hewan'
print(dict)

for key in sorted(dict.keys()):
    print(key,dict[key])

"""### Tuples and Dictionaries work Together

- line 1: create an empty dictionary for the input data; the student's name is used as a key, while all the associated scores are stored in a tuple (the tuple may be a dictionary value - that's not a problem at all)
- line 3: enter an "infinite" loop (don't worry, it'll break at the right moment)
- line 4: read the student's name here;
- line 5-6: if the name is exit, leave the loop;
- line 8: ask for one of the student's scores (an integer from the range 1-10)
- line 10-11: if the student's name is already in the dictionary, lengthen the associated tuple with the new score (note the += operator)
- line 12-13: if this is a new student (unknown to the dictionary), create a new entry - its value is a one-element tuple containing the entered score;
- line 15: iterate through the sorted students' names;
- line 16-17: initialize the data needed to evaluate the average (sum and counter)
- line 18-20: we iterate through the tuple, taking all the subsequent scores and updating the sum, together with the counter;
- line 21: evaluate and print the student's name and average score.
"""

schoolClass = {}

while True:
    name = input("Enter the student's name (or type exit to stop): ")
    if name == 'exit':
        break

    score = int(input("Enter the student's score (0-10): "))

    if name in schoolClass:
        schoolClass[name] += (score,)
    else:
        schoolClass[name] = (score,)

print(schoolClass)

for name in sorted(schoolClass.keys()):
    sum = 0
    counter = 0
    for score in schoolClass[name]:
        sum += score
        counter += 1
    print(name, ":", sum / counter)

def tf(sentence):
    d = {}
    for word in sentence.split():
        if word not in d:
            d[word] = 1
        else:
            d[word] += 1
    return d

kalimat = "Ibu pergi ke pasar dengan Bapak dan Ibu Ibu lain"
stopw.append('dan')
stopw.append('lain')
kalimat_stop = removeStop(kalimat.lower())
tf_kalimat = tf(kalimat_stop)

print(tf_kalimat)

"""# Summary

1. Dictionaries are unordered*, changeable (mutable), and indexed collections of data. (*In Python 3.6x dictionaries have become ordered by default.

Each dictionary is a set of key : value pairs. You can create it by using the following syntax:

```python            
myDictionary = {
    key1 : value1,
    key2 : value2,
    key3 : value3,
    }
```
2. If you want to access a dictionary item, you can do so by making a reference to its key inside a pair of square brackets (ex. 1) or by using the get() method (ex. 2):

```python                                                                                         
polEngDict = {
    "kwiat" : "flower",
    "woda"  : "water",
    "gleba" : "soil"
    }

item1 = polEngDict["gleba"]    # ex. 1
print(item1)    # outputs: soil

item2 = polEngDict.get("woda")
print(item2)    # outputs: water
```
3. If you want to change the value associated with a specific key, you can do so by referring to the item's key name in the following way:

```python
polEngDict = {
    "zamek" : "castle",
    "woda"  : "water",
    "gleba" : "soil"
    }

polEngDict["zamek"] = "lock"
item = polEngDict["zamek"]    # outputs: lock
```
4. To add or remove a key (and the associated value), use the following syntax:

```python
myPhonebook = {}    # an empty dictionary

myPhonebook["Adam"] = 3456783958    # create/add a key-value pair
print(myPhonebook)    # outputs: {'Adam': 3456783958}

del myPhonebook["Adam"]
print(myPhonebook)    # outputs: {}
```

You can also insert an item to a dictionary by using the update() method, and remove the last element by using the popitem() method, e.g.:

```python
polEngDict = {"kwiat" : "flower"}

polEngDict = update("gleba" : "soil")
print(polEngDict)    # outputs: {'kwiat' : 'flower', 'gleba' : 'soil'}

polEngDict.popitem()
print(polEngDict)    # outputs: {'kwiat' : 'flower'}
```

5. You can use the for loop to loop through a dictionary, e.g.:

```python
polEngDict = {
    "zamek" : "castle",
    "woda"  : "water",
    "gleba" : "soil"
    }

for item in polEngDict:
    print(item)    # outputs: zamek
                   #          woda
                   #          gleba

```



6. If you want to loop through a dictionary's keys and values, you can use the items() method, e.g.:


```python
polEngDict = {
    "zamek" : "castle",
    "woda"  : "water",
    "gleba" : "soil"
    }

for key, value in polEngDict.items():
    print("Pol/Eng ->", key, ":", value)
```


7. To check if a given key exists in a dictionary, you can use the in keyword:

```python
polEngDict = {
    "zamek" : "castle",
    "woda"  : "water",
    "gleba" : "soil"
    }

if "zamek" in polEngDict:
    print("Yes")
else:
    print("No")
```

8. You can use the del keyword to remove a specific item, or delete a dictionary. To remove all the dictionary's items, you need to use the clear() method:

```python
polEngDict = {
    "zamek" : "castle",
    "woda"  : "water",
    "gleba" : "soil"
    }

print(len(polEngDict))    # outputs: 3
del polEngDict["zamek"]    # remove an item
print(len(polEngDict))    # outputs: 2

polEngDict.clear()   # removes all the items
print(len(polEngDict))    # outputs: 0

del polEngDict    # removes the dictionary
```

9. To copy a dictionary, use the copy() method:

```python
polEngDict = {
    "zamek" : "castle",
    "woda"  : "water",
    "gleba" : "soil"
    }

copyDict = polEngDict.copy()
```

# Key Takeaways
"""

myTuple = (1, 2, True, "a string", (3, 4), [5, 6], None)
#print(myTuple)

myList = [1, 2, True, "a string", (3, 4), [5, 6], None]
#print(myList)

for r in myTuple[::-1]:
    print(r)

emptyTuple = ()
print(type(emptyTuple))    # outputs: <class 'tuple'>

myListTuple = list(myTuple)
print(myListTuple)
myTupleLagi = tuple(myListTuple)
print(myTupleLagi)

oneElemTup1 = ("one",  )    # brackets dan koma, kalau tidak ada komanya jadi string
oneElemTup2 = "one",     # no brackets, just a comma

print(type(oneElemTup1))
print(len(oneElemTup1+oneElemTup2))

oneElemList = ['one']
print(type(oneElemList))

# Example 1
t1 = (1, 2, 3)
for elem in t1:
    print(elem)

# Example 2
t2 = (1, 2, 3, 4)
print(5 in t2)
print(5 not in t2)

# Example 3
t3 = (1, 2, 3, 5)
print(len(t3))

# Example 4
t4 = t1 + t2
t5 = t3 * 2

print(t4)
print(t5)

import pprint
pp = pprint.PrettyPrinter(indent=4)

mahasiswa = [
    {
        'nim' : '08/123123/PA/123213',
        'nama' : 'Guntur Budi H',
        'nilai' : [80,90,75,30]
    },
    {
        'nim' : '08/213123/PA/98120',
        'nama' : 'Annisa Maulida N',
        'nilai' : [100,90,77,110]
    }
]
mahasiswa_baru = {
    'nim' : '12/12414/PA/12312',
    'nama' : 'Miftahhurahma Rosyda'
}

mahasiswa.append(mahasiswa_baru)
mahasiswa[0]['nilai'].append(79)
mahasiswa[2]['nilai'] = [80,100,95,25]

#pp.pprint(mahasiswa)
pp.pprint(mahasiswa[0]['nilai'][-1])

sinonim = open('files/sinonim.txt','r')
i = 1
for s in sinonim:
#     print(s)
    baris = s.split(':')
    print(baris)
    kata = baris[1].split(',')
    print(baris[0],kata)

"""sebuah_dict = {'Miftah':'Kurus'}
sebuah_dict['Miftah'] += ',Cantik'
print(sebuah_dict)
"""

paragraf = """
Kisah ini bermula dari seorang dewa dan seorang dewi yang karena kesalahan yang dibuatnya di kayangan, akhirnya harus menjalani hukuman di dunia. Keduanya dihukum untuk berbuat kebaikan dalam hidupnya di bumi dalam bentuk seekor babi hutan dan seekor anjing. Babi hutan jelmaan dewi itu bernama Wayung Hyang, sedangkan anjing jelmaan dewa itu bernama Tumang. Wayung Hyang karena dihukum sebagai babi hutan atau celeng, maka ia berusaha melakukan berbagai kebaikan di dalam sebuah hutan. Sementara Tumang, sang anjing jelmaan dewa itu mengabdi sebagai anjing pemburu pada seorang raja yang bernama Sumbing Perbangkara.
"""

#sintaks ini
kalimat = [k.strip().upper() for k in paragraf.split('.')] #memisahkan kalimat berdasarkan titik untuk menjadi list
# print(kalimat)

#sama dengan ini
kalimat_baru = []
for k in paragraf.split('.'):
    kalimat_baru.append(k.strip())
#     if k.endswith('dunia'):
#         print("Ada Dunia pada kalimat",k)

    if k.find('dunia'):
        print("Ada dunia pada kalimat",k)


#versi satu satu
kalimat_a = paragraf.split('.') #memisahkan kalimat berdasarkan titik di paragraf
kalimat_a[1] =  kalimat_a[1].strip() #menghilangkan spasi
kalimat_a[2] =  kalimat_a[2].strip() #menghilangkan spasi

k = "abu salam "
print(k.capitalize())
print(k.endswith("budi h"))