# -*- coding: utf-8 -*-
"""Python2-op_ifelse_iterasi_list_array.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bcDvETs7tisopAHbY3KSmUwkYPdTIdhM

# Python Basic 2
Boolean values, conditional execution, loops, lists and list processing, logical and bitwise operationsExternal tool

Referensi Tambahan:
- https://docs.python.org/3.8/
- https://docs.python.org/id/3.8/tutorial/


## Materi

- Operator relasional;
- Operator aritmatika;
- Struktur pemilihan if-elif-else;
- Struktur perulangan while dan for;
- Statement loncat;
- Operasi logika dan bitwise;
- Lists dan Array.

#### Mutable dan Immutable
Mutable : List, Dictionary

Immutable : String, Bilangan dan Tuple
"""

a=20
print(a)
print(id(a))

a=30
print(a)
print(id(a))

a=[1,2,3,4]
print(a)
print(type(a))
print(id(a))

a[0]=0
print(a)
print(id(a))

"""## Operator Relasional
Operator relasional adalah operator yang digunakan untuk membandingkan dua buah nilai. Hasil yang akan diperoleh dari operasi perbandingan ini adalah logika (bertipe bool), yaitu True (benar) atau False (salah).

![operator%20relasional.png](attachment:operator%20relasional.png)

### Prioritas Operator
| Prioritas| Operator |        |
|----------|----------|--------|
| 1        | +, -     | unary  |
| 2        | **       |        |
| 3        | *,/,//,% |        |
| 4        | +, -     | binary |

## Latihan: Questions and answers

Gunakan operator relasional untuk mendeteksi nilai integer < 100 atau >= 100

#### Test Data

Sample input: 55

`Expected output: False`

Sample input: 99

`Expected output: False`

Sample input: 100

`Expected output: True`

Sample input: 101

`Expected output: True`

Sample input: -5

`Expected output: False`

Sample input: +123

`Expected output: True`
"""

a=int(input("Sample input: "))
print("Expected output: ", a>=100)

"""# Operator Aritmatika

Operator aritmatika adalah operator yang digunakan untuk melakukan perhitungan terhadap data numerik. Berikut merupakan operator aritmatika yang digunakan dalam python :

![operator%20aritmatika.JPG](attachment:operator%20aritmatika.JPG)

</b> Prioritas operator </b>
Setiap operator aritmatika memiliki prioritas yang berbeda. Sebagai contoh :

</b> 3+5*7 </b>
Seperti yang diketahui, operator perkalian (*) memiliki prioritas yang lebih tinggi dibandingkan dengan operator penjumlahan (+) sehingga operasi dapat dituliskan sebagai berikut (3+(5*7)).

Untuk lebih jelasnya, tabel berikut memperlihatkan urutan prioritas dari operator aritmatika :
![prioritas.JPG](attachment:prioritas.JPG)

Berikut merupakan mindmap dari operasi aritmatika :

![mindmad%20aritmatika.JPG](attachment:mindmad%20aritmatika.JPG)

Perhatikan contoh dibawah :

x = 5 + 2 * 3 / (2 - 3) ** 2
berapa nilai x?
"""

x = 5 + 2 * 3 / (2 - 3) ** 2
print(x)

"""## Struktur Pemilihan

Berbeda dengan bahasa pemrograman lainnya, Python hanya memiliki satu statement untuk melakukan proses pemilihan, yaitu dengan menggunakan if. Untuk mempermudah pembahasan tentang statement if, pembahasan akan dibagi menjadi tiga kelompok :

 - Statement if untuk satu kasus
 - Statement if untuk dua kasus
 - Statement if untuk tiga kasus

### 1. Statement if untuk satu kasus

Bentuk umum penggunaan perintah if untuk satu kasus dalam Python adalah :

```python
if kondisi:
    statement1
    statement2
    ...
    
```
Pada bentuk diatas, statement1, statement2 dan seterusnya hanya akan dieksekusi jika kondisi yang didefinisikan dalam perintah If terpenuhi (bernilai True). Jika kondisi bernilai False, statement tersebut akan diabaikan oleh program.

Perhatikan contoh berikut :
"""

a = 5
b = 6

if a==b:
    print("oke")
    print("berhasil")
    print("Gagal")

"""### 2. Statement if untuk dua kasus

Untuk pemilihan yang mengandung dua kasus, bentuk umum yang digunakan adalah :

```python
if kondisi :
    statement1
    statement2
    ...
else
    statement_alternatif1
    statement_alternatif2
    ...
```

Pada bentuk ini, jika kondisi bernilai True makan statement selanjutnya yang akan dieksekusi oleh program adalah statement1, stetement 2 dan seterusnya. Tapi jika kondisi bernilai False, maka program akan mengeksekusi statement yang berada pada bagian else, yaitu statement_alternatif1, statement_alternatif2 dan seterusnya.
"""

a = 5
b = 6

if a==b:
    print("oke")
    print("berhasil")
else:
    print("Gagal")

"""#### Latihan 1
Memasukan bilangan bulat dan mendeteksi bilangan tersebut genap / ganjil.
"""

bil = int(input("Masukan bilangan bulat: "))

if(bil%2 == 0):
    print("genap")
else:
    print("ganjil")

"""### 3. Statement if untuk Tiga kasus atau lebih

Struktur pemilihan jenis ini merupakan bentuk yang paling kompleks jika dibandingkan dengan kedua jenis yang sudah di bahas diatas. Dalam struktur ini, ada beberapa kondisi yang harus diperiksa oleh program. Bentuk umum penggunaan perintah if untuk tiga kasus atau lebih adalah :

```python
if kondisi1:
    statement1a
    statement1b
    ...
elif kondisi2:
    statement2a
    statement2b
    ...
else:
    statement_alternatif1
    statement_alternatif2
    ...
```
Perhatikan contoh dibawah ini :

#### Latihan 2

![kuadran.jpg](attachment:kuadran.jpg)

Perhatikan gambar diatas. Penetuan kuadran dari suatu titik dilakukan dengan cara :

 - Jika x>0 dan y>0 maka titik akan berada pada Kuadran I
 - Jika x<0 dan y>0 maka titik akan berapa pada Kuadran II
 - Jika x<0 dan y<0 maka titik akan berada pada Kuadran III
 - JIka x>0 dan y<0 maka titik akan berada pada Kuadran IV
 - Jika keepat kondisi ini tidak dapat dipenuhi, maka titik tidak termasuk pada kuadran manapun

Tuliskan kondisi tersebut dalam bahasa Python.
"""

print("Masukan nilai koordinat")
x = int(input("Nilai x: "))
y = int(input("Nilai y: "))

if x>0 and y>0:
    print("Koordinat ("+ str(x) + ","+ str(y) +") berada pada Kuadran I" )
elif x<0 and y>0:
    print("Koordinat ("+ str(x) + ","+ str(y) +") berada pada Kuadran II" )
elif x<0 and y<0:
    print("Koordinat ("+ str(x) + ","+ str(y) +") berada pada Kuadran III" )
elif x>0 and y<0:
    print("Koordinat ("+ str(x) + ","+ str(y) +") berada pada Kuadran IV" )
else:
    pass

"""#### Latihan 3
Mencari bilangan terbesar, dari 3 inputan (a, b dan c)
"""

num1 = int(input("First Number : "))
num2 = int(input("Second Number : "))
num3 = int(input("Third Number : "))

#set number1 sebagai yang terbesar
largestNum = num1

#deteksi apakah num2 > num1
if num2 > largestNum:
    largestNum = num2

#deteksi apakah num3 > num2
if num3 > largestNum:
    largestNum = num3

print("The largest number is: ", largestNum)

"""## Latihan
Spathiphyllum, atau yang sering disebut dengan 'peace lily' atau tanaman 'white sail merupakan tanaman dalam rumah yang sangat populer yang dapat menjadi filter guna menyaring udara dari racun. Beberapa racun yang dapat di filter adalah benzena, fomaldehyde, dan amonia.

Bayangkan bahwa program komputer anda sangat menyukai tanaman. Ketika komputer menerima masukan (input) pada form "Spathiphyllum", maka komputer akan merespon dengan "Spathiphyllum is the best plant ever!".

Tulislah sebuah program dengan Python untuk beberapa kondisi berikut, input adalah sebuah string :

- respon komputer :  `"Yes - Spathiphyllum is the best plant ever!"` ketika input berupa `"Spathiphyllum"` (upper-case)
- respon komputer :  `"No, I want a big Spathiphyllum!"` ketika input berupa `"spathiphyllum"` (lower-case)
- respon komputer :  `"Spathiphyllum! Not [input]!"` ketika input berupa "input".
"""

plant = input("Please input a best plant = ")

if plant == "Spathiphyllum":
    print("Yes - Spathiphyllum is the best plant ever!")
elif plant == "spathiphyllum":
    print("No, I want a big Spathiphyllum!")
else:
    print("Spathiphyllum! Not "+ plant +"!")

"""## Latihan


Pada suatu masa terdapat sebuah daratan - daratan dengan susu dan madu, yang dihuni oleh masyarakat yang bahagia dan sejahtera. Masyarakat tersebut membayar pajak, sehingga kebahagiaan mereka memiliki batas. Pajak yang paling penting adalah Personal Income Tax atau disebut PIT yang mana harus dibayarkan tiap tahun, dan dievaluasi dengan peraturan sebagai berikut :  

- Jika penghasilan tidak lebih besar daripada 85,528 thaler, maka pajak adalah sebesar 18% dari pemasukan dikurangi 556 thaler dan 2 sen (disebut juga tax relief)
- Jika penghasilan lebih dari nilai tersebut, maka pajak adalah sebesar 14,839 thaler and 2 cents, ditambah 32% dari selisih penghasilan dengan 85,528 thalers.

Tugas anda adalah membuat <b>tax calculator</b>.

- Harus menerima satu masukan : penghasilan
- Berikutnya, print pajak yang telah dihitung, nilai dibulatkan penuh ke thaler (tanpa sen). Fungsi round() akan membantu anda untuk membulatkan nilai.

Catatan : Negara yang bahagia ini tidak pernah mengembalikan uang tersebut ke warganya. Jika perhitungan pajak kurang dari nol, itu berarti warga tidak dikenakan pajak sama sekali (pajak = 0).
    
Perhatikan syntax dibawah ini, hanya membaca satu input dan output sebagai hasilnya. Lengkapi syntax tersebut dengan sebuah perhitungan yang cerdas.

```python
income = float(input("Enter the annual income: "))

#
# Put your code here.
#

tax = round(tax, 0)
print("The tax is:", tax, "thalers")
```

Test your code using the data we've provided.

```python
Sample input: 10000

Expected output: The tax is: 1244.0 thalers
        
Sample input: 100000

Expected output: The tax is: 19470.0 thalers
        
Sample input: 1000

Expected output: The tax is: 0.0 thalers

Sample input: -100

Expected output: The tax is: 0.0 thalers
"""

income = float(input("Enter the annual income: "))
tax = 0

if income<85528:
    tax = 0.18 * income - 556.2
else:
    tax = 14839 + 0.2 + 0.32 * (income - 85528)

tax = round(tax, 0)

if tax<0:
    tax = 0

print("The tax is:", tax, "thalers")

"""## Latihan

As you surely know, due to some astronomical reasons, years may be leap or common. The former are 366 days long, while the latter are 365 days long.

Since the introduction of the Gregorian calendar (in 1582), the following rule is used to determine the kind of year:

- if the year number isn't divisible by four, it's a common year;
- otherwise, if the year number isn't divisible by 100, it's a leap year;
- otherwise, if the year number isn't divisible by 400, it's a common year;
- otherwise, it's a leap year.

Look at the code in the editor - it only reads a year number, and needs to be completed with the instructions implementing the test we've just described.

``` python
year = int(input("Enter a year: "))

#
# Put your code here.
#

```

The code should output one of two possible messages, which are Leap year or Common year, depending on the value entered.

It would be good to verify if the entered year falls into the Gregorian era, and output a warning otherwise: Not within the Gregorian calendar period. Tip: use the != and % operators.

Test your code using the data we've provided.

Sample input: `2000`

Expected output: `Leap year`

Sample input: `2015`

Expected output: `Common year`

Sample input: `1999`

Expected output: `Common year`

Sample input: `1996`

Expected output: `Leap year`

Sample input: `1580`

Expected output: `Not within the Gregorian calendar period`
"""

year = int(input("Enter a year: "))

if year < 1582:
    print("Not within the Gregorian calender period")
else :
    if year % 4 !=0 :
        print("common year")
    elif year % 100 !=0:
        print ("leap year")
    elif year % 400 !=0:
        print("common year")
    else :
        print("leap year")

"""#### Latihan-latihan

Apakah luaran dari syntax berikut :
"""

x = 5
y = 10
z = 8

print(x > y)
print(y > z)

x, y, z = 5, 10, 8

print(x > z)
print((y - 5) == x)

x, y, z = 5, 10, 8
x, y, z = z, y, x

print(x > z)
print((y - 5) == x)

x = 10

if x == 10:
    print(x == 10)

if x > 5:
    print(x > 5)

if x < 10:
    print(x < 10)
else:
    print("else")

x = "1"

if x == 1:
    print("one")
elif x == "1":
    if int(x) > 1:
        print("two")
    elif int(x) < 1:
        print("three")
    else:
        print("four")

if int(x) == 1:
    print("five")
else:
    print("six")

x = 1
y = 1.0
z = "1"

if x == y:
    print("one")
if y == z:
    print("two")
    print(x)
    print(y)
elif x == y:
    print("three")
else:
    print("four")

"""## 3.2 Struktur perulangan

Python menyediakan dua statement untuk melakukan proses perulangan yaitu for dan while. Diantara kedua statement ini, secara umum for lebih banyak digunakan daripada while.

### 1. Statement while

Sama seperti kebanyakan bahasa pemrograman lainnya, Python juga mendukung statement while untuk melakukan perulangan satu atau sekelompok statement. Bentuk umum dari perulangan while adalah sebagai berikut :

```python
while kondisi:
    statement1
    statement2
    statement1
    :
    :
    statementn
```
Pada bentuk perulangan diatas, statement1, statement2 dan seterusnya merupakan sekelompok statement yang akan diulang. Statement tersebut akan terus dieksekusi/ diulang selama kondisi bernilai True. Maka diperlukan sebuah statement yang akan bernilai False, agar proses dapat berhenti. Perhatikan syntax berikut :

"""

i = 1

while i<10:
    print(i**2)
    i = i+2

"""#### Perhatikan contoh program untuk menghitung berapa ganjil dan genap dari rangkaian bilangan :"""

# program that reads a sequence of numbers
# and counts how many numbers are even and how many are odd
# program terminates when zero is entered

oddNumbers = 0
evenNumbers = 0

# read the first number
number = int(input("Enter a number or type 0 to stop: "))

# 0 terminates execution
while number != 0:
    # check if the number is odd
    if number % 2 == 1:
        # increase the oddNumbers counter
        oddNumbers += 1
    else:
        # increase the evenNumbers counter
        evenNumbers += 1
    # read the next number
    number = int(input("Enter a number or type 0 to stop: "))

# print results
print("Odd numbers count:", oddNumbers)
print("Even numbers count:", evenNumbers)

"""## Latihan
A junior magician has picked a secret number. He has hidden it in a variable named `secretNumber`. He wants everyone who run his program to play the Guess the secret number game, and guess what number he has picked for them. Those who don't guess the number will be stuck in an endless loop forever! Unfortunately, he does not know how to complete the code.

Your task is to help the magician complete the code in the editor in such a way so that the code:

- will ask the user to enter an integer number;
- will use a `while` loop;
- will check whether the number entered by the user is the same as the number picked by the magician. If the number chosen by the user is different than the magician's secret number, the user should see the message `"Ha ha! You're stuck in my loop!"` and be prompted to enter a number again. If the number entered by the user matches the number picked by the magician, the number should be printed to the screen, and the magician should say the following words: `"Well done, muggle! You are free now."`

```python
secretNumber = 777

print(
'''
+================================+
| Welcome to my game, muggle!    |
| Enter an integer number        |
| and guess what number I've     |
| picked for you.                |
| So, what is the secret number? |
+================================+
''')
```

The magician is counting on you! Don't disappoint him.
"""

secretNum = 777

guessNum = 0

while guessNum != secretNum:
    guessNum = int(input("Input angka rahasia untuk berhenti : "))
    if guessNum != secretNum:
        print("Perulangan akan terus lanjut...")

print("Well done, Congrats...")

"""### 2. Statement for

Selain menggunakan statement while, kita juga dapat melakukan perulangan dengan statement for. Perintah for biasanya digunakan untuk mengambil atau menelusuri data (item) yang terdapat pada tipe-tipe koleksi seperti string, list, tuple, dictionary dan set. Dalam pemrograman, proses penelusuran data dalam sebuah koleksi disebut iterasi. Selain itu, for juga dapat melakukan perulangan normal (sama seperti while), yaitu dengan menggunakan fungsi range(). Dengan menggunakan range(), kita akan dapat dengan mudah melakukan perulangan dari indeks awal ke indeks tertentu.

Bentuk perintah for dapat dituliskan sebagai berikut :

1. Statement for untuk perintah koleksi
```python
for indeks tipe koleksi:
    statement1
    statement2
    ...
```
2. Statement for untuk rentang nilai tertentu
```python
for indeks in range (nilai_awal, nilai_akhir, step):
    statement1
    statement2
    ...
```
Perhatikan contoh-contoh dibawah ini :
"""

for i in range(5):
    print(i)

for i in range(2,8):
    print(i)

for i in range(2,18,3):
    print(i)

for i in range(5):
    print(i)
else:
    print("masuk else")

"""## Latihan


Do you know what Mississippi is? Well, it's the name of one of the states and rivers in the United States. The Mississippi River is about 2,340 miles long, which makes it the second longest river in the United States (the longest being the Missouri River). It's so long that a single drop of water needs 90 days to travel its entire length!

The word Mississippi is also used for a slightly different purpose: to count mississippily.

If you're not familiar with the phrase, we're here to explain to you what it means: it's used to count seconds.

The idea behind it is that adding the word Mississippi to a number when counting seconds aloud makes them sound closer to clock-time, and therefore "one Mississippi, two Mississippi, three Mississippi" will take approximately an actual three seconds of time! It's often used by children playing hide-and-seek to make sure the seeker does an honest count.


Your task is very simple here: write a program that uses a for loop to "count mississippily" to five. Having counted to five, the program should print to the screen the final message "Ready or not, here I come!"

Use the skeleton we've provided in the editor.

```python
import time

# Write a for loop that counts to five.
    # Body of the loop - print the loop iteration number and the word "Mississippi".
    # Body of the loop - use: time.sleep(1)

# Write a print function with the final message.
```

<strong> EXTRA INFO </strong>

Note that the code in the editor contains two elements which may not be fully clear to you at this moment: the import time statement, and the sleep() method. We're going to talk about them soon.

For the time being, we'd just like you to know that we've imported the time module and used the sleep() method to suspend the execution of each subsequent print() function inside the for loop for one second, so that the message outputted to the console resembles an actual counting. Don't worry - you'll soon learn more about modules and methods.
"""

import time

for i in range(5):
    print(i," Missisipi")
    time.sleep(1)

"""### 3. Statement Loncat

Statement loncat merupakan perintah yang digunakan untuk memindahkan eksekusi program dari satu bagian tertentu ke bagian lain. Python menyediakan tiga statement yaitu : break, continue dan return.

#### 3.1 Statement break

Statement break digunakan untuk menghentikan secara paksa proses perulangan, meskipun kondisi perulangan sebenarnya masih bernilai True. Perhatikan contoh-contoh berikut ini :
"""

for i in range (11):
    print(i, end=" ")
    if i==7:
        print(" masih dalam for")
        break

# break - example

print("The break instruction:")
for i in range(1, 6):
    if i == 3:
        break
    print("Inside the loop.", i)
print("Outside the loop.")

largestNumber = -99999999
counter = 0

while True:
    number = int(input("Enter a number or type -1 to end program: "))
    if number == -1:
        break
    counter += 1
    if number > largestNumber:
        largestNumber = number

if counter != 0:
    print("The largest number is", largestNumber)
else:
    print("You haven't entered any number.")

"""#### 3.2 Statement continue

Statement continue berguna untuk memaksa pengulangan agar memroses indeks selanjutnya meskipun statement didalam blok pengulangan sebenarna belum semua di eksekusi. Dengan kata lain, statement yang ada dibawah statement continue akan diabaikan (tidak dieksekusi)
"""

for i in range (1,11):
    if i % 2 ==0:
        continue
    print(i, end="\t")

for i in range (1,11):
    if i % 2 ==0:
        print(i)

# continue - example

print("\nThe continue instruction:")
for i in range(1, 6):
    if i == 3:
        continue
    print("Inside the loop.", i)
print("Outside the loop.")

largestNumber = -99999999
counter = 0

number = int(input("Enter a number or type -1 to end program: "))

while number != -1:
    if number == -1:
        continue
    counter += 1

    if number > largestNumber:
        largestNumber = number
    number = int(input("Enter a number or type -1 to end program: "))

if counter:
    print("The largest number is", largestNumber)
else:
    print("You haven't entered any number.")

"""## Latihan

The `break` statement is used to exit/terminate a loop.

Design a program that uses a `while` loop and continuously asks the user to enter a word unless the user enters `"chupacabra"` as the secret exit word, in which case the message `"You've successfully left the loop."` should be printed to the screen, and the loop should terminate.

Don't print any of the words entered by the user. Use the concept of conditional execution and the break statement.
"""

while True:
    word = input("Masukkan Sebuah Kata untuk keluar dari perulangan = ")
    if(word=="chupacabra"):
        break

print("You've successfully left the loop")

"""## Latihan


The `continue` statement is used to skip the current block and move ahead to the next iteration, without executing the statements inside the loop.

It can be used with both the while and for loops.

Your task here is very special: you must design a vowel eater! Write a program that uses:

- a for loop;
- the concept of conditional execution (if-elif-else)
- the continue statement.

Your program must:

- ask the user to enter a word;
- use `userWord = userWord.upper()` to convert the word entered by the user to upper case; we'll talk about the so-called string methods and the `upper()` method very soon - don't worry;
- use conditional execution and the `continue` statement to "eat" the following vowels A, E, I, O, U from the inputted word;
- print the uneaten letters to the screen, each one of them on a separate line.

```python
# Prompt the user to enter a word
# and assign it to the userWord variable.

for letter in userWord:
    # Complete the body of the for loop.
```

Test your program with the data we've provided for you.


Test data

Sample input: `Gregory`

Expected output:
```
G
R
G
R
Y
```
Sample input: `abstemious`

Expected output:
```
B
S
T
M
S
```
"""

# Prompt the user to enter a word
# and assign it to the userWord variable.
userWord = input("Masukkan sebuah kata = ")

for letter in userWord:
    if letter.upper() in ['A','I','U','E','O']:
        continue

    print(letter.upper())

"""## Latihan

Listen to this story: a boy and his father, a computer programmer, are playing with wooden blocks. They are building a pyramid.

Their pyramid is a bit weird, as it is actually a pyramid-shaped wall - it's flat. The pyramid is stacked according to one simple principle: each lower layer contains one block more than the layer above.

The figure illustrates the rule used by the builders:
```
=
==
===
```
blocks : 6
height : 3
Your task is to write a program which reads the number of blocks the builders have, and outputs the height of the pyramid that can be built using these blocks.

Note: the height is measured by the number of fully completed layers - if the builders don't have a sufficient number of blocks and cannot complete the next layer, they finish their work immediately.

Test your code using the data we've provided.

Sample input: 6

Expected output: The height of the pyramid: 3

Sample input: 20

Expected output: The height of the pyramid: 5

Sample input: 1000

Expected output: The height of the pyramid: 44

Sample input: 2

Expected output: The height of the pyramid: 1
"""

blocks = int(input("Enter the number of blocks: "))
current_block = 0
height = 0
i=0

while i<blocks:
    height += 1
    current_block += height
    # print(i,current_block)
    if current_block> blocks:
        break

height -= 1

print("The height of the pyramid:", height)

"""### Latihan

1. Buatlah perulangan dengan menggunakan for yang mulai dari 0 sampai dengan 10, dan cetak nomer ganjil pada layar.

2. Buatlah perulangan dengan menggunakan while dari 0 sampai dengan 10, dan cetak nomer ganjil pada layar

3. Buatlah sebuah program dengan perulangan for dan statement break. Program harus diiterasi sebanyak jumlah karakter didalam sebuah alamat email, dan loop akan berhenti jika menemukan simbol '@' dan cetak karakter yang ditemukan sebelum simbol '@' didalam sebuah line

4. Buatlah sebuah perulangan loop dan statement continue. Program harus diiterasi sebanyak nomer yang ditemukan dalam string (digit = "0165031806510"), ganti 0 dengan x, lalu cetak string yang telah dimodifikasi.
"""

for i in range(1, 11):
    if i % 2 !=0:
        print(i,end=' ')

x=1
while x<11:
    if x % 2 !=0:
        print(x,end=' ')
    x +=1

for ch in "ratna.lestari@ugm.ac.id":
    if ch == "@":
        break
    print(ch,end=' ')

for digit in "0165031806510":
    if digit == "0":
        print ("x")
        continue
    print(digit)

"""#### Apakah output dari kode-kode berikut?"""

n = 3

while n > 0:
    print(n + 1)
    n -= 1
else:
    print(n)

n = range(4)

for num in n:
    print(num - 1)
else:
    print(num)

for i in range(0, 6, 3):
    print(i)

"""## 3.3 Operasi Logika

Operasi Logika `and`

| Argument A | Argument B | A and B |
|------------|------------|---------|
| False      | False      | False   |
| False      | True       | False   |
| True       | False      | False   |
| True       | True       | True    |

Operasi Logika `or`

| Argument A | Argument B | A or B |
|------------|------------|--------|
| False      | False      | False  |
| False      | True       | True   |
| True       | False      | True   |
| True       | True       | True   |

Operasi Logika `not`

| Argument | not Argument |
|----------|--------------|
| False    | True         |
| True     | False        |

> If we have some free time, <b>and</b> the weather is good, we will go for a walk

> If you are in the mall <b>or</b> I am in the mall, one of us will buy a gift for Mom.

Perhatikan contoh dibawah ini :
"""

x = 1
y = 0

z = ((x == y) and (x == y)) or not(x == y)
print(not(z))

"""## 3.4 List dan Array

Tipe list dalam python sebenernya mirip dengan array normal pada bahasa pemrograman lain. List juga dapat menampung beberapa tipe data sekaligus.

Bentuk umum untuk membuat list dalam python adalah :

```python

nama_list = [nilai1, nilai2, nilai3,...]
```

Perhatikan contoh dibawah ini :
"""

var1=1
var2=2
var3=3
var4=4
var5=5

#bandingkan

var=[1,2,3,4,5]
print(var)

"""### Indexing List
Dalam list, elemen tidak diindeks berdasarkan key tertentu yang namanya bisa didefinisikan sendiri melainkan berdasarkan indeks bilangan yang diawali dengan nilai nol(0). Perhatikan contoh berikut :
"""

num = [2,3,4,5]
print(num)
print(num[2])
print(num[-1])

"""Indeks dapat juga bernilai negatif yaitu menghitung indeks mulai dari kanan. Perhatikan contoh berikut :"""

lst = [100,200,300,400,500]
print(lst[-1])
print(lst[-2])
print(lst[-5])

print("\n")
print(lst[4])
print(lst[3])
print(lst[0])

"""## Slicing List"""

lst=[4,1,6,9,10,8]

print(lst[0:3])
print(lst[1:3])

print(lst[-3:])
print(lst[:-3])

print(lst[:])

"""### Swap

Nilai elemen didalam list selain dapat diakses juga dapat dimanipulasi dengan swapping. Perhatikan contoh berikut :
"""

num=[2,3,4]
num[0],num[1] = num[1], num[0]
print(num)

"""#### Bubble Short
![BubbleSort_worst_case.gif](attachment:BubbleSort_worst_case.gif)
"""

myList = [8, 10, 6, 2, 4] # list to sort
swapped = True # it's a little fake - we need it to enter the while loop

while swapped:
    swapped = False # no swaps so far
    for i in range(len(myList) - 1):
        if myList[i] > myList[i + 1]:
            swapped = True # swap occured!
            myList[i], myList[i + 1] = myList[i + 1], myList[i]

print(myList)

"""### Lab 3.4.1.6: The basics of lists
There once was a hat. The hat contained no rabbit, but a list of five numbers: 1, 2, 3, 4, and 5.

Your task is to:

- write a line of code that prompts the user to replace the middle number in the list with an integer number entered by the user (step 1)
- write a line of code that removes the last element from the list (step 2)
- write a line of code that prints the length of the existing list (step 3.)
Ready for this challenge?
"""

hatList = [1, 2, 3, 4, 5]  # This is an existing list of numbers hidden in the hat.

# Step 1: write a line of code that prompts the user
# to replace the middle number with an integer number entered by the user.

# Step 2: write a line of code here that removes the last element from the list.

# Step 3: write a line of code here that prints the length of the existing list.

print(hatList)

"""### Menambah Elemen ke dalam list

Terdapat tiga cara untuk menambahkan elemen baru kedalam sebuah list yaitu :

 - Menggunakan metode append() : Metode ini digunakan untuk menambah elemen tunggal dibagian akhir list. Perhatikan contoh dibawah :
"""

buah=["Salak","Mangga","Apel"]
buah.append("Jeruk")
print(buah)

myList = [] # creating an empty list

for i in range(5):
    myList.append(i + 1)

print(myList)

"""`Menggunakan metode insert() : Metode ini digunakan untuk menambah elemen tunggal di indeks / posisi tertentu. Perhatikan contoh dibawah :`"""

buah = ["durian", "mangga", "apel"]
buah.insert(1,"kiwi")
print (buah)

numbers = [111, 7, 2, 1]
print(len(numbers))
print(numbers)

###

numbers.append(4)

print(len(numbers))
print(numbers)

###

numbers.insert(0, 222)
print(len(numbers))
print(numbers)

#

"""### Menghapus Elemen kedalam list

Menghapus elemen dapat dilakukan dengan :

```python
nama_list.remove(nilai)
```

atau dengan memberikan indeksnya menggunakan instruksi delete :

```python
del nama_list[indeks]
"""

num = [5,4,3,2,1]

del num[1]
print(num)

"""## Latihan

The Beatles were one of the most popular music group of the 1960s, and the best-selling band in history. Some people consider them to be the most influential act of the rock era. Indeed, they were included in Time magazine's compilation of the 20th Century's 100 most influential people.

The band underwent many line-up changes, culminating in 1962 with the line-up of John Lennon, Paul McCartney, George Harrison, and Richard Starkey (better known as Ringo Starr).


Write a program that reflects these changes and lets you practice with the concept of lists. Your task is to:

- step 1: create an empty list named `beatles`;
- step 2: use the `append()` method to add the following members of the band to the list: `John Lennon`, `Paul McCartney`, and `George Harrison`;
- step 3: use the `for` loop and the `append()` method to prompt the user to add the following members of the band to the list: `Stu Sutcliffe`, and `Pete Best`;
- step 4: use the `del` instruction to remove `Stu Sutcliffe` and `Pete Best` from the list;
- step 5: use the `insert()` method to add `Ringo Starr` to the beginning of the list.
By the way, are you a Beatles fan?
"""

# step 1
beatles = []
print("Step 1:", beatles)

# step 2
beatles.append("John Lennon")
beatles.append("Paul McCartney")
beatles.append("George Harrison")
print("Step 2:", beatles)

# step 3
for i in range(2):
    nama = input("Masukkan anggota baru = ")
    beatles.append(nama)
print("Step 3:", beatles)

# step 4
del beatles[-2:]
print("Step 4:", beatles)

# step 5
beatles.insert(0,"Ringo Starr")
print("Step 5:", beatles)


# testing list legth
print("The Fab", len(beatles))

"""## Tambahan Method"""

lst = [5, 1, 3, 2, 10]
print(lst)
lst.sort()
print(lst)
lst.reverse()
print(lst)

vehiclesOne = ['car', 'bicycle', 'motor']
print(vehiclesOne) # outputs: ['car', 'bicycle', 'motor']

vehiclesTwo = vehiclesOne
del vehiclesOne[0] # deletes 'car'
print(vehiclesTwo) # outputs: ['bicycle', 'motor']
print(vehiclesOne)

vehiclesOne = ['car', 'bicycle', 'motor']
print(vehiclesOne) # outputs: ['car', 'bicycle', 'motor']

vehiclesTwo = vehiclesOne[:]
del vehiclesOne[0] # deletes 'car'
print(vehiclesTwo) # outputs: ['bicycle', 'motor']
print(vehiclesOne)

nama = ["Ana","Budi","Citra"]
kata_kunci = "Budi"

print(kata_kunci not in nama)

if kata_kunci in nama:
    print("Nama "+kata_kunci+" ada di list")

for i in range(10):
    print(i, end=" ")

print()
for i in range(1,7):
    print(i, end=" ")

print()
for i in range(1,10,2):
    print(i, end=" ")

print()
for i in range(10,-10,-2):
    print(i, end=" ")

for i in range(1, 11):
    if i%2 != 0:
        print(i, end=" ")

x = 1
while x < 11:
    if x%2!=0:
        print(x, end=" ")
    x += 1

for ch in "john.smith@pythoninstitute.org":
    if ch == "@":
        break
    print(ch,end="")

for digit in "0165031806510":
    if digit == "0":
        print("x",end="")
        continue
    print(digit,end="")

"""### List Method (Advance)

Perhatikan contoh berikut :
"""

myList = [10, 1, 8, 3, 5]
total = 0

for i in range(len(myList)):
    total += myList[i]

print(total)

#squares = [x ** 2 for x in range(10)]
#print (squares)

squares = []
for x in range(10):
    squares.append(x ** 2)
print(squares)

twos = [2 ** i for i in range(8)]
print(twos)

squares = []
odds = [x for x in squares if x % 2 != 0 ]
print (odds)

# sama dengan
odds = []
for x in squares:
    if x % 2 != 0:
        odds.append(x)
print (odds)

"""### List Dua Dimensi (Array)

List dapat berisi berbagai tipe data seperti strings, boolean maupun list lainnya. Kita sering sekali menemukan bentuk array seperti ini dikehidupan kita, salah satu contohnya adalah papan catur. Papan catur terdiri dari baris dan kolom, terdapat 8 baris dan juga 8 kolom. Setiap kolom ditandai oleh huruf A sampai dengan H, dan setiap baris ditandai oleh 1 sampai dengan 8.

Perhatikan kode berikut :
"""

# Contoh List di dalam List
i = [2,3,4,5]
print(i[0])

k = [[3,5,1],[6,1,8],[9,10,4]]
print(k)
print(k[1])
print(k[1][0])
print(k[-1][-2:])

EMPTY = "-"
board = []

for i in range(8):
    row = [EMPTY for i in range(8)] #membuat satu list
    board.append(row) #membuat 8 list
    print(row)
#print(board)

"""List diatas menggambarkan list papan catur yang masih kosong sebagaimana gambar ilustrasi dibawah :

![rook.JPG](attachment:rook.JPG)

Mari kita isi list sersebut dengan sesuatu yang kita inginkan. Perhatikan kode berikut :
"""

EMPTY = "-"
LIMALIMA = "LIMA"
ROOK = "ROOK"
KNIGHT = "KNIGHT"
PAWN = "PAWN"
board = []

for i in range(8):
    row = [EMPTY for i in range(8)]
    board.append(row)

#isi dengan ROOK
board[0][0] = ROOK
board[5][5] = LIMALIMA
board[0][7] = ROOK
board[7][0] = ROOK
board[7][7] = ROOK

#isi dengan KNIGHT
board[4][2] = KNIGHT

#isi dengan PAWN
board[3][4] = PAWN


print(board)
print("\n")

"""#### List Multidimensi (Array)

Untuk mencari sebuah elemen pada list dua dimensi adalah dengan menggunakan dua koordinat yaitu nomer baris dan juga nomer kolom. Bayangkan ketika anda akan mengembangkan sebuah program untuk perekam cuaca otomatis. Alat ini akan mampu merekam suhu udara tiap jam sampai dengan satu bulan. Maka total data yang akan direkam adalah 24 jam x 31 hari = 744 data.

Pertama-tama, kita harus memutuskan tipe data yang akan tepat untuk aplikasi ini. Pada kasus ini, tipe float adalah yang paling sesuai karena suhu biasanya diukur sampai dengan akurasi satu dibelakang koma (0.1). Selanjutnya, kita akan menentukan bahwa baris akan merepresentasikan jam (sehingga ada 24 baris) dan setiap baris akan direpresentasikan untuk satu hari (sehingga kita membutuhkan lagi 31 baris).
"""

temps = [[0.0 for h in range(2)] for d in range(4)]
print (temps)

temps = [[0.0 for h in range(24)] for d in range(31)]

# 1. the monthly average noon temperature
sum = 0.0

for day in temps:
    sum += day[11]

average = sum / 31

print("Average temperature at noon:", average)

# 2. the highest temperature during the whole month
highest = -100.0

for day in temps:
    for temp in day:
        if temp > highest:
            highest = temp

print("The highest temperature was:", highest)

# 3.count the days when the temperature at noon was at least 20 ℃
hotDays = 0

for day in temps:
    if day[11] > 20.0:
        hotDays += 1

print(hotDays, "days were hot.")

"""#### 3. Array tiga dimensi

Python tidak memiliki batasan dalam list-in-list. Ini merupakan contoh untuk array tiga dimensi.

Bayangkan sebuah hotel yang besar terdiri dari tiga bangunan, 15 lantai untuk tiap  bangunannya. Pada setiap lantai terdapat 20 kamar.

Langkah pertama adalah tentukan tipe data dari array yang akan dibuat. Dalam kasus ini nilai Boolean yang paling sesuai, nilai True jika kamar telah di pesan dan nilai False jika kamar kosong. Langkah kedua adalah dengan menganalisa kondisi yang diberikan.

Kode dibawah akan menghasilkan array :
"""

rooms = [[[False for r in range(2)] for f in range(3)] for t in range(4)]
print (rooms)

"""Coba berikan input untuk kondisi bibawah ini :
1. Pesan satu kamar pada gedung 2, lantai 10, kamar 14
2. Kosongkan satu kamar pada gedung 1, lantai 5, kamar 2
3. Periksa apakah ada kamar kosong di lantai 15
"""

rooms = [[[False for r in range(20)] for f in range(15)] for t in range(3)]

rooms[1][9][13] = True
rooms[0][4][1] = False

print(rooms)

vacancy = 0

for roomNumber in range(20):
    if not rooms[2][14][roomNumber]:
        vacancy += 1

print(roomNumber)